{% set name = "pyswarms" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyswarms-{{ version }}.tar.gz
  sha256: 1204aa9c332c662113e3c37d1b109906f4a0859b29ded80c1582dc66387ce34b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - attrs
    - future
    - matplotlib-base >=1.3.1
    - numpy
    - python >={{ python_min }}
    - pyyaml
    - scipy
    - tqdm

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - pyswarms
  commands:
    - pip check

about:
  doc_url: https://pyswarms.readthedocs.io/en/latest/
  home: https://github.com/ljvmiranda921/pyswarms
  summary: A Python-based Particle Swarm Optimization (PSO) library.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ljvmiranda921
    - hakonanes
